Added recipe selection UI for Transfer Assembler
DRKV333/MechTransfer pull request #10
Opened 2021-12-28 14:22 UTC by Ved-s

![изображение](https://user-images.githubusercontent.com/53968411/147575812-fdd10112-e35a-4f2b-a239-bb9065730304.png)

2021-12-31 16:45 UTC, DRKV333 requested changes
Overall, I like the idea, but the implementation could be improved a bit.

There are a few bugs. Scrolling on an assembler with no item set causes an exception. Sometimes the selection seems to scroll backwards (so scrolling up moves the selection down).

The recipe selection should not be shown every time an assembler is hovered, it takes up too much space. Also, I'm not sure if having it always active could cause someone to accidentally change recipes, while trying to scroll their hotbar.
So, the recipe selection should probably only be shown, once someone starts scrolling. Or, only show and activate the whole scrolling feature, once an item is right-clicked into the assembler, to make sure they meant it.
Also, either way, scrolling should be suppressed for other parts of the game UI, while the recipe selection is active.

I'm not entirely sold on the recipe hashing. Wouldn't it be easier to just store the actual recipe, serialize the result and ingredients on save, and find the corresponding real recipe from the loaded ones on load?

The whole architecture could be better, the `SyncSpecificData` part and the way this new `AssemblesHoverUI` copies a lot of things from the original `FilterHoverUI`, is a bit messy. That is partially my fault for not making this system generic enough. Some things could be factored out into base classes, but if you don't want to mess with that, this is fine by me too.

Some formatting issues should be fixed, see comments for examples.

2021-12-31 16:45 UTC, DRKV333 commented on MechTransfer.cs
> +
Remove this empty space.

2021-12-31 16:45 UTC, DRKV333 commented on UI/RecipeUI.cs
> +                    break;
For loops should always have braces.

2021-12-31 16:45 UTC, DRKV333 commented on Tiles/TransferAssemblerTile.cs
> +                    }
Ifs should have braces on all branches, or none of them.

2021-12-31 16:45 UTC, DRKV333 commented on Tiles/TransferAssemblerTile.cs
> +            if (!TryGetEntity(i, j, out TransferAssemblerTileEntity entity)) return;
Statements after ifs should start on a new line.

2021-12-31 16:45 UTC, DRKV333 commented on Tiles/TransferAssemblerTile.cs
> +                        goto StartScrollHandling;
Please don't use goto.

2022-01-01 16:04 UTC, Ved-s commented
I messed up branches at my repo a bit, but I think, I resolved it

2022-01-07 06:24 UTC, Ved-s commented
Packet routing in the mod needs to be completely reworked, I can't send any additional data from AssemblerTE without fully overriding FilterTE's SyncData code

2022-01-07 06:49 UTC, closed without merging

2022-01-07 06:49 UTC, Ved-s commented
Frick it, i hate visual studio

2022-01-07 13:25 UTC, DRKV333 commented
I can also recommend VSCode, if you prefer a lighter editor.
I don't have the time right now to work on this mod, and fix things in your PR, but I hope we can pick this up later.